foundation-model-stack/fms-guardrails-orchestrator

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/user_story.md
- CODEOWNERS
- CONTRIBUTING.md
1. Add codeowners
2. Add contributing guidelines
> Add contributing readme

- src/orchestrator.rs
> Fix chunk offset

- src/clients/detector.rs
- src/orchestrator.rs
> Fix response ordering, drop Option from DetectorRequest parameters

- docs/api/openapi_detector_api.yaml
- src/clients/detector.rs
> :technologist: Add text to contents analysis detectors response API

- docs/api/orchestrator_openapi_0_1_0.yaml
- Add new orchestrator endpoint and API spec to support additional types of detector following their API available here: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/blob/main/docs/api/openapi_detector_api.yaml
> :sparkles: Add new API spec for new orchestrator detection endpoints to support other types of detectors

- README.md
> :memo: Document logging

- Cargo.toml
- src/server.rs
Crypto provider apparently needs a default
Ref: 
- https://github.com/rustls/hyper-rustls/blob/main/examples/server.rs
- https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html
> :bug: Provide a default crypto provider

- docs/architecture/adrs/003-detector-api-design.md
closes: #71 
Add ADR documenting detector API decisions.
> :memo::iphone: Add ADR describing detector API

- src/clients/chunker.rs
- Renamed `bidi_streaming_tokenize_whole_doc` to `tokenize_whole_doc_stream` and simplified signature
- Updated `tokenize_whole_doc_stream` logic to be more efficient
- Avoids loop and excess allocations, should be at least 3-5x faster
- Dropped unneeded `tokio::spawn()`
- Added unit tests for `tokenize_whole_doc` and `tokenize_whole_doc_stream`
> Tweak streaming whole doc chunker efficiency, add unit tests

- src/clients.rs
- src/clients/chunker.rs
- src/clients/detector.rs
- src/clients/generation.rs
- src/clients/nlp.rs
- src/clients/tgis.rs
- src/config.rs
- src/lib.rs
- src/main.rs
- src/models.rs
- src/orchestrator.rs
- src/orchestrator/aggregators/mod.rs
- src/orchestrator/errors.rs
- src/orchestrator/streaming.rs
- src/orchestrator/unary.rs
- src/server.rs
- Add copyright notices to all source code files.
> :page_facing_up: Add copyright notice to all orchestrator source files

- src/orchestrator/aggregators/max_processed_index.rs
Supports: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/57
- Add `DetectionTracker` namedtype to help with max aggregator processing
- Add logic for this processor
- Add unit test
> Add max process aggregator

- protos/caikit_runtime_Chunkers.proto
- src/clients/chunker.rs
- src/orchestrator/aggregators/max_processed_index.rs
- src/orchestrator/aggregators/mod.rs
- src/orchestrator/streaming.rs
- src/orchestrator/unary.rs
- Update chunker proto spec to include input index tracking
- Update stream and unary files to represent new chunker task
- Update aggregator to use result from generation response directly to populate fields
- Add aggregation of tokens, if present
> :sparkles: Update chunker API with token pointer support and modify aggregator accordingly

- docs/architecture/adrs/004-orchestrator-input-only-api-design.md
closes: #104 
This PR documents the ADR for orchestrator API and specially the new endpoints and nomenclature exposed.
> :memo: Add orchestrator API ADR

- src/orchestrator/aggregators/max_processed_index.rs
This PR fixes below issues:
- Chunkers response are inclusive w.r.t end_index_pointer and the logic was excluding that resulting in last value not getting considered for final response.
- Seed value is only present in 1st response from generation providers, so we need to extract it from there as we do for `input_token_count`
> :bug: Fix last response missing and incorrect seed value problem

- src/clients.rs
> :wrench: Increase default timeouts

- config/config.yaml
- docs/api/openapi_detector_api.yaml
- src/clients/detector.rs
- src/models.rs
- src/orchestrator/unary.rs
closes: #161 
- Add evidences section in `DetectionResult` for orchestrator response
> Add evidences context

- src/orchestrator/unary.rs
- Fix offset for standalone content endpoint.
> :bug: Fix offset for standalone content results

- config/config.yaml
Provide more inline description for orchestrator config sections for users
> :bulb: Add config description

- src/clients.rs
- src/clients/chunker.rs
- src/config.rs
- src/orchestrator.rs
- src/orchestrator/streaming.rs
- src/orchestrator/unary.rs
closes: #228 
- Add `whole_doc_chunker` client as default client for chunkers
> :bug: Fix whole_doc_chunker missing from client list

- Cargo.lock
- Cargo.toml
- tests/common/detectors.rs
- tests/common/orchestrator.rs
- tests/detection_on_generation.rs
- tests/streaming_classification_with_gen_nlp.rs
- tests/test_config.yaml
- tests/text_content_detection.rs
- Updates mocktail to `0.2.3-alpha` (breaking changes)
- Updates existing tests to the new mocktail API
- Adds tests for `/api/v2/text/detection/generated` (closes #315)
> Update existing integration tests to new mocktail API, add tests for `/api/v2/text/detection/generated`

- tests/classification_with_text_gen.rs
- tests/common/orchestrator.rs
- tests/generation_with_detection.rs
> Generation with detection integration tests

- Cargo.lock
- Cargo.toml
- src/clients/detector/text_contents.rs
- src/clients/openai.rs
- src/models.rs
- src/orchestrator/common/tasks.rs
- src/orchestrator/streaming_content_detection/aggregator.rs
- src/orchestrator/unary.rs
- tests/chat_detection.rs
- tests/classification_with_text_gen.rs
- tests/context_docs_detection.rs
- tests/detection_on_generation.rs
- tests/generation_with_detection.rs
- tests/streaming_classification_with_gen.rs
- tests/text_content_detection.rs
> Replace HashMap with BTreeMap

- src/server.rs
- tests/common/orchestrator.rs
- tests/streaming_classification_with_gen.rs
- tests/streaming_content_detection.rs
> Stream content tests and error handling fix

- tests/streaming_classification_with_gen.rs
- tests/streaming_content_detection.rs
Addresses #359, with exception of chat_completions endpoint as streaming has not been implemented yet.
> Single detector tests

- tests/common/orchestrator.rs
> Implement re-try logic for TestOrchestratorServer port binding

- Cargo.lock
- Cargo.toml
Working around merge conflict issue, it's needed for #391
> Add dashmap dependency

- src/clients/openai.rs
This fixes an issue with capturing and handling errors from the downstream server. To properly handle errors, we need to match the response status code in `handle_streaming()` _prior to_ converting the body to a data stream and ultimately SSE event stream. Also added a few comments.
This caused certain errors to be silently ignored and the task to continue execution (leading to other errors) when it should have been terminated.
For example, in the case of `prompt_logprobs: true` being requested when `stream: true` (which is unsupported), the task should have failed and returned an error event with 422 and the error message from vLLM as shown below. Instead, the task continued execution and later returned a 500 error.
```
event: error
data: {"code":422,"details":"chat completion request …
```
> Fix OpenAiClient error handling for streaming

- src/clients/openai.rs
- src/models.rs
- src/orchestrator/handlers/chat_completions_detection/unary.rs
- tests/chat_completions_detection.rs
> Empty choice warning

- config/config.yaml
> :wrench: Update config key and comments

- Dockerfile.amd64
Thanks, @declark1, for noticing this.
> Fix rust version for amd64 build

- src/orchestrator/handlers/completions_detection/streaming.rs
Closes #482
This PR removes the code that adds an unnecessary extra message with `finish_reason`. While this is needed for chat_completions, it is not needed for completions as the last message from vLLM sends both, `text` and `finish_reason`.
> fix: do not send additional stop message for completions
