foundation-model-stack/fms-guardrails-orchestrator

- build.rs
- protos/caikit_runtime_Chunkers.proto
- protos/caikit_runtime_Nlp.proto
- src/clients.rs
- src/clients/chunker.rs
- src/orchestrator.rs
Use a separate chunkers client for the chunker API (assumes a Chunker Service as opposed to an NLP service)
Closes: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/30
> :sparkles: Chunkers client

- docs/api/openapi_detector_api.yaml
- Divide detectors API into multiple endpoints to cover more variety of detectors.
- This PR only updates the detectors API documentation for easy sharing of the API.
Note: API is still in iteration and we will update the orchestrator client once its finalized / stable in story #37
> :technologist: Iterate over detectors API to include multiple endpoints

- Cargo.toml
- src/clients.rs
- src/clients/chunker.rs
- src/clients/detector.rs
- src/clients/nlp.rs
- src/clients/tgis.rs
- src/config.rs
- src/lib.rs
- src/orchestrator.rs
- src/orchestrator/errors.rs
- src/server.rs
This PR implements initial error handling using 3 layers of errors:
1. `clients::Error` is a low-level error that wraps grpc and http client errors.
- Implements `status_code()` method to return the actual (http client) or mapped (grpc client) http status code. This is useful for pattern-matching specific types of errors.
2. `orchestrator::Error` contains variants for issues that may arise during processing of tasks, such as `DetectorNotFound`, `DetectorRequestFailed`, etc. We can extend this as-needed.
3. `server::Error` is a high-level error returned to the caller, enabling them to react accordingly to validation and not found errors from the orchestrator and downstream services.
- Implements `axum::IntoResponse` to return 422 for validation-type errors (with a detailed message), 404 …
> Implement error handling

- docs/api/openapi_detector_api.yaml
- Replace `content` endpoint to support `batch` operation by default.
> :technologist: Replace content endpoint with batch endpoint

- docs/api/openapi_detector_api.yaml
- Fix title names for the content analysis request response
> :bug: Fix title of objects in detector API spec

- docs/architecture/adrs/001-orchestrator.md
> :memo: Update ADR with threshold information

- docs/api/openapi_detector_api.yaml
closes: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/54
- Rename `prompt` to Content` for context analysis detector API
> :technologist: Rename prompt to content for context analysis API

- docs/api/openapi_detector_api.yaml
- docs/api/orchestrator_openapi_0_1_0.yaml
- Update error object in detectors API to fix data type of `code`
> :technologist: Update error object in API to fix data type for code

- docs/api/openapi_detector_api.yaml
`evidences` by its plurality was meant to be an array, but this was unclear from the spec
> :bug: Evidences as array

- src/orchestrator.rs
I thought of a more efficient way to do this. Renamed to `slice_codepoints`. Also updated `apply_masks` to use `slice_codepoints`.
> Renamed index_codepoints to slice_codepoints and updated to do it cleaner

- config/config.yaml
- src/clients.rs
- src/config.rs
using a single bundle cert was already implemented at https://github.com/foundation-model-stack/fms-guardrails-orchestrator/blob/4973351d25f7954aed8475f0b40b00678d071eb6/src/clients.rs#L113
I tested running the local PII with mTLS and self signed certificated.
> tests added and enable self signed certs #69

- README.md
I'm running a Fedora 40 machine and I had multiple errors when trying to run `cargo install --path .`
I realized these error messages were related to missing dependencies so, once I managed to successfully run the command on my machine, I spinned up a [Fedora 40 container](https://hub.docker.com/_/fedora) to figure out what where the packages needed to successfully compile the project.
This PR updates the README with the required dependencies to successfully build the project.
> Documenting dependencies to install project on Fedora

- src/server.rs
supports: #39 
- Add package info in healthcheck endpoint to allow easy introspection in deployment
> :sparkles: Add package info in healthcheck endpoint

- src/server.rs
Follow-up to #92 - mTLS builder also needs default crypto provider so this line had to move up
> :bug: Update for mTLS builder

- Dockerfile
Adding `compat-openssl11` to the image seems to fix #113 (thanks, @declark1!).
> Add ssl package to Dockerfile

- docs/api/orchestrator_openapi_0_1_0.yaml
- src/models.rs
- src/orchestrator/aggregators/max_processed_index.rs
- Make `start_index` optional, similar to `processed_index` so that the values can be null when this APi is used as generation only, i.e no model is provided
- Make `input_token_count` and `input_tokens` to be present in only 1st / 2nd streamed response, similar to text-generation API behavior, instead of all the streamed responses.
- Make `seed` present in first and last streamed responses
> :bug: Fix presence of seed, input_token and token count in streaming resp

- src/models.rs
- src/orchestrator.rs
- src/orchestrator/unary.rs
- src/server.rs
This addresses #124.
No unit tests were added as most of the code is reused from the `/api/v1/task/classification-with-text-generation` endpoint was reused. We will add integration tests for this endpoint once we start working on these.
> Implement `/api/v1/text/task/detection/content` endpoint

- docs/api/orchestrator_openapi_0_1_0.yaml
- docs/architecture/adrs/004-orchestrator-input-only-api-design.md
- src/models.rs
- src/orchestrator.rs
- src/server.rs
As per team discussion, we want to rename new APIs and put them under `v2` to better align
> :truck: Rename orchestrator API to v2

- src/clients/detector.rs
Discovered that an error returned in unexpected form, e.g. a 503 error page with html formatting from the router, can cause a deserialization error resulting in a 500 to the client instead of the actual triggering error code.
> Fix: handle detector client error deserialization error

- docs/api/orchestrator_openapi_0_1_0.yaml
- src/clients/detector.rs
- src/models.rs
- src/orchestrator.rs
- src/orchestrator/unary.rs
- src/server.rs
This addresses #123. One important point to add is that `context_type` only accepts values "docs" or "url".
Scenarios tested:
* Sample request -> works just fine (base success scenario).
* Missing `context` -> returns 422
* Missing `context_type` -> returns 422
* Missing `detectors` -> returns 422
* Two detectors -> returns detections from both detectors (though the order of detections may vary)
* Threshold filtering -> only detections above the threshold are returned
* Detector returning 404 -> returns 404
* Detector returning 503 -> returns 503
* Detector returning 500 (further details are shown on logs) -> returns 500
* Detector returning 422 -> returns 422
> Implementation of /context endpoint

- Cargo.lock
- Cargo.toml
- src/clients.rs
- src/main.rs
Related to (not fully understood) breaking change in tonic 0.12.0 [#1731](https://github.com/hyperium/tonic/pull/1731), which is causing connection timeout in our TLS-enabled tonic clients.
> Configure explicit tls roots for tonic client

- src/models.rs
- src/orchestrator/streaming.rs
- src/orchestrator/unary.rs
Updates `DetectorParams` to be a newtype wrapper over `HashMap<String, serde_json::Value>`, enabling parameter flexibility across detector implementations. Includes a `threshold()` convenience method as this parameter is applied by the orchestrator.
> Update DetectorParams to newtype wrapper

- docs/api/openapi_detector_api.yaml
- docs/api/orchestrator_openapi_0_1_0.yaml
- docs/architecture/adrs/003-detector-api-design.md
- docs/architecture/adrs/004-orchestrator-input-only-api-design.md
- src/clients/detector.rs
- src/orchestrator/aggregators/max_processed_index.rs
- src/orchestrator/unary.rs
This updates the detector API according to the structure as discussed in #159 . For now, `evidence` is expected for the "context docs" orchestrator endpoint i.e. `/text/detection/context`, so only the `DetectionContextDocsResponse` has been updated. As more detectors expose `evidence`, this can be added to the other orchestrator endpoints. One layer of nesting is required for now to expose the information needed by "context docs" endpoint users, but this should be the limit of nesting [more could get even more confusing].
It seems `evidence` is "uncountable" and would account for plurality, so I have updated the API references as so to not refer to "evidences"
Exposing `evidence` through the orchestrator endpoint and actual integration/testing with the "context docs" endpoint will be part …
> :memo: Update evidence for detector API and context docs

- src/models.rs
- src/orchestrator/unary.rs
- We were currently sending out `TokenClassificationResult` for `/content` endpoint, which is incorrect as per the agreed upon API spec. This PR fixes that by adding a separate `detect_content` function that provides this response object.
> :bug: Fix content standalone endpoint response object

- src/clients/chunker.rs
- src/clients/generation.rs
- src/config.rs
- src/lib.rs
- src/main.rs
- src/orchestrator.rs
- src/server.rs
For Issue https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/23
- introduced config error type variants
- made `tls`, `chunkers` and `generation` config sections optional
- `tls` may also be provided inlined to a service config
- `chunkers` can be omitted, in which case the default `"whole_doc_chunker"` chunker will be subsidized
- `generation` as a whole may be omitted from configuration
- support for and error handling of optional generation client configuration
- implemented validation logic and error handling for tls config mapping
- added more config validation tests for error handling
> Orchestrator Service Config Validation

- src/clients.rs
closes: #197 
- This PR attempts at adding slightly more information to http errors returned by `reqwest` library. 
For cert errors we would only see following in log:
```
error received from detector detector_id=<DETECTOR_ID>error=Http { code: 500, message: "error sending request for url (https://<URL>:8000/api/v1/text/contents)" 
```
For misconfigured port we would see:
```
error received from detector detector_id=<DETECTOR_ID>error=Http { code: 500, message: "error sending request for url (https://<URL>:8000/api/v1/text/contents)" 
```
For cert error:
```
http request failure. source: client error (SendRequest)
```
For misconfigured port:
```
http request failure. source: client error (Connect)
```
ATM it doesn't seem there is a way to easily get more descriptive error messages from …
> :loud_sound: Add http error source logging

- Cargo.lock
- build.rs
- src/main.rs
Supports: #213 
- Turn off default health startup check
- Fix `tonic-build` `compile_protos` deprecation issue by updating the package and changing `compile` to `compile_protos`
> 🔧 Turnoff default health check

- docs/api/openapi_detector_api.yaml
From #211 and before, there hasn't been the concept of `context` for the chat endpoint. Removing the reference to avoid confusion
> :wrench: Remove context from chat endpoint in detector API

- src/clients/detector/text_chat.rs
- src/models.rs
- src/orchestrator.rs
- src/orchestrator/unary.rs
- src/server.rs
This addresses #210. Messages can be either strings or text content types.
Tests performed:
1. Accepts string messages
2. Accepts text content type messages
3. Rejects image content type messages
4. Propagates 404 messages from detectors.
5. Propagates 503 messages from detectors.
6. Propagates 422 messages from detectors.
7. Returns error 500 when detectors return messages not compliant with [the API](https://foundation-model-stack.github.io/fms-guardrails-orchestrator/?urls.primaryName=Detector+API#/default/chat_analysis_unary_handler_api_v1_text_chat_post).
> Chat standalone endpoint

- src/clients/openai.rs
- src/orchestrator.rs
- src/orchestrator/chat_completions.rs
- src/orchestrator/chat_completions_detection.rs
- src/server.rs
This PR implements the OpenAI Chat Completions Detections API (no detections).
- Conditionally enables the chat completions detection endpoint (`/api/v2/chat/completions-detection`) if chat generation config is provided
- Adds `ChatCompletionsDetectionTask` and `Orchestrator::handle_chat_completions_detection` handler that calls `OpenAiClient::chat_completions()` (handles both unary and streaming)
As `orchestrator/unary.rs` is getting _very_ large, starting with this, I've created a standalone file `orchestrator/chat_completions_detection.rs` for the handler. It also feels weird to add this to "unary" as its both a unary and streaming endpoint. I suggest that we consider opening a PR to split the other handlers into their own files as we have added many new endpoints.
Closes #192
> Implement Chat Completions API

- src/clients/chunker.rs
- src/clients/detector.rs
- src/config.rs
- src/lib.rs
Small PR to expose modules and types publicly for integration tests. Also adds `ServiceConfig::new` method for convenience.
Closes #265
> Expose modules and types publicly for integration tests, add ServiceConfig::new

- src/models.rs
- src/orchestrator/chat_completions_detection.rs
- src/orchestrator/detector_processing/content.rs
- src/server.rs
**Story:**  [foundation-model-stack/fms-guardrails-orchestrator#261](https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/261)
This PR adds a container attribute from the serde framework to handle unknown fields passed into to a request for ochestrator APIs. A unit test is also added asserting the case used for the scenario used in the git issue.  
In addition to the unit test, each endpoint was modified to have a field name with a typo, or an outright made up field, and compared with an older orchestrator version deployed on openshift, versus the locally modified version. 
Example:
```
curl --request POST   --url 'http://localhost:8033/api/v1/task/server-streaming-classification-with-text-generation'  --header 'Content-Type: application/json'  --data '{"inputs": …
```
> Add error handling for unknown fields in orchestrator request

- Cargo.lock
- Cargo.toml
- src/clients/detector.rs
- Upgrade UUID [was originally removed as unused in #281 but was not upgraded after being added back]
- Add a new `x-model-name` header to be a used by an optional router component, if available. The decision was made to always just add this header, as opposed to adding more configuration or conditional logic.
Debug log example [some details obscured] - full requests are not on info level
```
2025-01-22T20:33:04.638671Z DEBUG incoming_orchestrator_http_request{request_method="POST" request_path="/api/v1/task/server-streaming-classification-with-text-generation" response_status_code=200 request_duration_ms=2}:stream_classification_with_gen{model_id="my-llm"}:handle_streaming_classification_with_gen{trace_id="f466fbf7eb4c46ea987530d5fbb624f9" model_id="my-llm" …
```
> :wrench: Add header on detector requests

- src/clients.rs
- src/config.rs
- Make grpc probe configurable per client
- Fix default connect timeout
> :wrench: Make grpc dns probe interval configurable per client

- Cargo.toml
- src/server.rs
**Story:**  [foundation-model-stack/fms-guardrails-orchestrator#294](https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/294)
This PR processes the orchestrator stream-content endpoint request as a stream of newline-delimited JSON messages.
The axum_extra::json_lines extractor is used in the handler  to buffer, split, and deserialize messages.
Additionally, this PR adds a new error, `UnsupportedContentType` use to validate `Content-Type`, and this case, is used to enforce the content-type is application/x-ndjson in the request.
This was tested locally, using the following commands to verify the content-type validation, and the output of the messages: 
Regular message: 
```
curl -X 'POST' \
>   'http://localhost:8033/api/v2/text/detection/stream-content' \
>   -H …
```
> process stream-content requests as ndjson (w/jsonlines)

- docs/architecture/adrs/010-detection-batcher.md
- src/orchestrator.rs
- src/orchestrator/common.rs
- src/orchestrator/common/utils.rs
- src/orchestrator/types.rs
- src/orchestrator/types/chat_message.rs
- src/orchestrator/types/chunk.rs
- src/orchestrator/types/detection.rs
- src/orchestrator/types/detection_batch_stream.rs
- src/orchestrator/types/detection_batcher.rs
- src/orchestrator/types/detection_batcher/chat_completion.rs
- src/orchestrator/types/detection_batcher/max_processed_index.rs
- src/orchestrator/types/detection_batcher/noop.rs
No. 2 of a few small pre-refactor PRs. This PR adds a new `orchestrator.types` module, including new abstractions used in the refactored code.
- `Chunk` 
- An internal chunk, used for both unary and streaming
- `Chunks`
- A newtype representing a vec of `Chunk`s
- `Detection` 
- An internal detection, used for all detector types
- `Detections`
- A newtype representing a vec of `Detection`s
- `DetectionBatchStream`
- A stream adapter that wraps multiple detection streams and produces a stream of batches using one of the pluggable `DetectionBatcher` implementations below. 
- More details to be added to this PR explaining the rationale and how this works.
- `DetectionBatcher`
- A trait to implement pluggable batching logic for `DetectionBatchStream`
- `MaxProcessedIndexBatcher` 
- A …
> pre-refactor: Add orchestrator.types module with common types

- src/server.rs
- src/utils.rs
- src/utils/json.rs
- tests/canary_test.rs
- tests/text_content_detection.rs
This PR reverts the response stream handling for the stream content detection to remove the bug introduced during validation for the detectors field when jsonlines was used as response.
The bug was seen with the following request: 
```
curl -X 'POST' \
'http://localhost:8033/api/v2/text/detection/stream-content' \
-H 'accept: application/x-ndjson' \
-H 'Content-Type: application/x-ndjson' \
-d '{"content": "hello"}'
curl: (18) transfer closed with outstanding read data remaining
```
The expected response is the following: 
`{'code': 422, 'details': '`detectors` is required for the first message'}`
The problem is how processing of the errors occurs in jsonlines which requires prior error mapping and serialization. Going back to the original code will remove the regressive behavior.
> reverted response_stream processing and message json conversion for stream content detection

- Cargo.lock
- tests/common/detectors.rs
- tests/common/orchestrator.rs
- tests/context_docs_detection.rs
- tests/test_config.yaml
> Integration tests for input detections in `/api/v2/text/detection/context/`

- tests/chat_detection.rs
- tests/common/detectors.rs
- tests/common/orchestrator.rs
- tests/test_config.yaml
> Integration tests for `/api/v2/text/detection/chat`

- Cargo.toml
- src/config.rs
- src/orchestrator/chat_completions_detection.rs
- src/orchestrator/common.rs
- src/orchestrator/common/client.rs
- src/orchestrator/common/tasks.rs
- src/orchestrator/common/utils.rs
- src/orchestrator/errors.rs
- src/orchestrator/types.rs
- src/server.rs
- Adds 2 new modules for the refactor:
- `common.tasks`: functionality reusable across task handlers
- `common.clients`: client call helper functions
- Adds `configure_mock_servers()` to `common.utils` for unit tests
- Other changes:
- Renames `Error::ChatGenerateRequestFailed` to `Error::ChatCompletionRequestFailed` (more accurate)
- Adds `Error::ChunkerNotFound` variant
- Adds `chunker()` and `detector()` convenience methods to `OrchestratorConfig`
- Updates config types to implement `Default` always rather than just in a test cfg. The compiler was giving me problems using `configure_mock_servers()` without doing this. I don't see any issue with these types implementing `Default` anyways.
1. This includes an initial set of unit tests for the functions that will be used by the first 2 …
> pre-refactor: Add common.tasks and common.clients modules

- docs/api/openapi_detector_api.yaml
- src/clients/detector/text_contents.rs
- src/models.rs
- src/orchestrator/common/tasks.rs
- src/orchestrator/streaming_content_detection/aggregator.rs
- src/orchestrator/types/detection.rs
- src/orchestrator/unary.rs
- tests/chat_detection.rs
- tests/classification_with_text_gen.rs
- tests/context_docs_detection.rs
- tests/detection_on_generation.rs
- tests/generation_with_detection.rs
- tests/streaming_classification_with_gen.rs
- tests/text_content_detection.rs
closes: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/338
- Add metadata to `DetectionResult` 
- Add metadata to standalone detection swagger spec examples
```
curl --request POST \
--url http://localhost:8038/api/v2/text/detection/content \
--header 'Content-Type: application/json' \
--data '{
"detectors": {
"granite-guardian-content": {
}
},
"content":"Your email is test@ibm.com! Hi, Only the next instance of email will be processed. test@ibm.com. Your SSN is 123-45-6789."
}'
```
```
{
"detections": [
{
"start": 0,
"end": 121,
"text": "Your email is test@ibm.com! Hi, Only the next instance of email will be processed. test@ibm.com. Your SSN is 123-45-6789.",
"detection": "Yes",
"detection_type": "risk",
"detector_id": "granite-guardian-content",
"score": …
```
> Add metadata object

- Dockerfile
For `CIS_Docker_v1.5.0 - 4.6` compliance - generally we do not use docker for healthchecking
> :construction_worker: Healthcheck command for Dockerfile

- src/config.rs
- src/orchestrator/common/utils.rs
- src/orchestrator/handlers/chat_completions_detection/unary.rs
- src/orchestrator/handlers/chat_detection.rs
- src/orchestrator/handlers/classification_with_gen.rs
- src/orchestrator/handlers/context_docs_detection.rs
- src/orchestrator/handlers/detection_on_generation.rs
- src/orchestrator/handlers/generation_with_detection.rs
- src/orchestrator/handlers/streaming_classification_with_gen.rs
- src/orchestrator/handlers/streaming_content_detection.rs
- src/orchestrator/handlers/text_content_detection.rs
- src/utils.rs
- tests/chat_completions_detection.rs
- tests/chat_detection.rs
- tests/classification_with_text_gen.rs
- tests/common/detectors.rs
- tests/context_docs_detection.rs
- tests/detection_on_generation.rs
- tests/generation_with_detection.rs
- tests/streaming_classification_with_gen.rs
- tests/streaming_content_detection.rs
- tests/test_config.yaml
- tests/text_content_detection.rs
Closes #352, and also adds appropriate integration tests.
> Guardrails request config validation

- src/orchestrator/types/detection_batch_stream.rs
- src/orchestrator/types/detection_batcher.rs
- src/orchestrator/types/detection_batcher/chat_completion.rs
- src/orchestrator/types/detection_batcher/max_processed_index.rs
- src/orchestrator/types/detection_batcher/noop.rs
This PR refactors the `DetectionBatchStream` implementation to resolve the bug noted in #378. As part of the solution, a `DetectionBatcherManager` actor has been implemented to own and manage the batcher to avoid using locks as both push and pop operations require mutable borrows and pops are happening in a loop to get new batches as they become ready.
Notes: 
- I'm currently testing and comparing 2 slightly different implementations: (1) separate batcher and detection receiver tasks and (2) single task approach. This PR currently uses (2).
- Two small updates will need to be made to #380 for this:
- Add `#[derive(Debug, Clone)]` to `ChatCompletionBatcher`
- Add `is_empty()` to `impl DetectionBatcher for ChatCompletionBatcher`:
```rust
fn is_empty(&self) -> bool {
self.state.is_empty()
} …
```
> Fix DetectionBatchStream

- Cargo.lock
- Cargo.toml
Closes #395.
[Diff of changes](https://github.com/gkumbhat/ginepro/commit/654898d0b552cabb6a3ba159dc1639934b0e637c) required to upgrade Tonic.
> Upgrade tonic to 0.13.1

- src/orchestrator/handlers/chat_completions_detection/streaming.rs
There are scenarios where this is valid, so this PR drops the warning log message when there is no choice content as this is fine.
e.g.
- The first message's choice only includes `role: assistant` with no content
- The final message with the stop reason may not include content
- Likely other scenarios
> Drop warning for empty choice content

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/utils/trace.rs
Updates open telemetry crates to the current latest (0.30.0 for most, and 0.31.0 for tracing-opentelemetry).
> Upgrade open telemetry crates to 0.30

- Cargo.lock
- Cargo.toml
- src/server/tls.rs
Updated dependencies with `cargo upgrade`.
In addition, the crate `rustls-webpki` had [breaking changes](https://github.com/rustls/webpki/releases/tag/v%2F0.103.0). I had to add `rustls-pki-types` as a dependency to manage that.
> Upgrade dependencies

- Dockerfile.amd64
- Dockerfile.s390x
Closes #422.
Summary:
1. Removed linting and formatting steps.
2. Moved testing to previous stage and copied `tests` folder content.
3. Replaced `cargo install` with `cargo build --release` to create the orchestrator binary.
> Test s390x build

- src/orchestrator/handlers/chat_completions_detection/streaming.rs
This PR fixes an issue where non-empty choice text was being sent to the detection input channel
> fix: only send non-empty choice text to detection input channel

- src/orchestrator/handlers/chat_completions_detection/streaming.rs
This PR updates the chat completions streaming handler to send `None` to the response channel on errors that terminate the task early. `None` is used to signal that the `[DONE]` message should be sent.
> fix: send [DONE] after all error messages

- config/config.yaml
- src/config.rs
- src/orchestrator.rs
- src/orchestrator/common/utils.rs
- src/orchestrator/handlers/chat_completions_detection/streaming.rs
- src/orchestrator/handlers/chat_completions_detection/unary.rs
- src/server/routes.rs
- tests/chat_completions_detection.rs
- tests/common/orchestrator.rs
With the upcoming work to support Open AI's completions endpoint, we should rename the orchestrator config file entry to `openai`, as it will be used for other endpoints rather than just chat completions.
> Rename `chat_completions` config to `openai`

- src/clients/openai.rs
- tests/chat_completions_detection.rs
Addresses https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/452 by generalizing the `stop_reason` field to an untagged `String` and `i64` enum.
> Bugfix: Allow int/string stop_reasons

- Cargo.lock
- Cargo.toml
- src/orchestrator/common/tasks.rs
- tests/chat_completions_streaming.rs
- tests/chat_completions_unary.rs
- tests/chat_detection.rs
- tests/classification_with_text_gen.rs
- tests/completions_detection.rs
- tests/context_docs_detection.rs
- tests/detection_on_generation.rs
- tests/generation_with_detection.rs
- tests/streaming_classification_with_gen.rs
- tests/streaming_content_detection.rs
- tests/text_content_detection.rs
This PR upgrades mocktail to `0.3.0` and updates tests to use `MockServer::new_grpc()` as the `.grpc()` builder method has been deprecated. While optional, this also updates tests to use `MockServer::new_http()`, preferred over less explicit `MockServer::new()`.
Closes #454
> Upgrade mocktail to 0.3.0, update tests to use new MockServer constructors

- src/orchestrator/handlers/chat_completions_detection/streaming.rs
- src/orchestrator/types.rs
- src/orchestrator/types/completion_state.rs
- tests/chat_completions_streaming.rs
Changes:
- Add `CompletionState` and drop `ChatCompletionState` **
- This type holds state for streaming completions tasks and is now generic over the completion chunk type (`ChatCompletionChunk`, `Completion`) to reduce code duplication.
- A few tweaks/enhancements:
- Moved `usage` out of metadata as it isn't a metadata field
- Replaced `Mutex` with `OnceLock` as `metadata` and `usage` are only set once, from the _first message_ and _usage message_, respectively
- Error will be intentionally disregarded if they are set again, but this shouldn't happen anyway
- Added convenience methods to improve ergonomics: `set_metadata`, `set_usage`, `insert_completion`
- Update logic to detect the _usage message_ for setting "final" `usage` state
- The existing logic didn't work when …
> Add Chat Completions Streaming support for continuous_usage_stats

- src/clients/openai.rs
- src/orchestrator/handlers/chat_completions_detection/streaming.rs
- src/orchestrator/handlers/chat_completions_detection/unary.rs
- src/orchestrator/handlers/completions_detection/streaming.rs
- src/orchestrator/handlers/completions_detection/unary.rs
- tests/chat_completions_streaming.rs
- tests/chat_completions_unary.rs
- tests/completions_detection.rs
nit: this PR renames detection types common to completions and chat completions for alignment. We are now using "completion" naming for common types. Also assigns better names to associated types.
`OpenAiDetections` -> `CompletionDetections` (this type is for completions/chat completions detections specifically)
`InputDetectionResult` -> `CompletionInputDetections`
`OutputDetectionResult` -> `CompletionOutputDetections`
`OrchestratorWarning` -> `CompletionDetectionWarning`
> Rename openai detection types

- Cargo.lock
- Dockerfile.amd64
- Dockerfile.ppc64le
- Dockerfile.s390x
For image provenance purposes, we have been asked to leverage Red Hat registry images for the builder layer as well as the release layer - here we leverage UBI 9 minimal. The latest RHEL (9.6) uses `1.84.1` Rust and Cargo, so we still install `rustup` via `curl` to leverage the latest versions (1.88 currently).
The existing Rust toolchain from `rust-toolchain.toml` is leveraged.
`amd64` has been tested with this PR but all architectures have been updated to enable Red Hat image building. Other architectures may have to be tested/debugged by other individuals or teams with access.
> :construction_worker: Update builder layer to use UBI 9 minimal

- src/clients/openai.rs
- src/orchestrator/handlers/completions_detection/streaming.rs
- src/orchestrator/handlers/completions_detection/unary.rs
This PR adds a `prompt_masks` field to `CompletionsRequest` (provided by user as `_prompt_masks`) and updates completions input detection handlers to apply masks. This is a "hidden" feature to maintain parity with `guardrail_config.input.masks` from classification-with-text-generation.
e.g.  the following will only detect the first phone number
```json
{
"model": "example-0b",
"prompt": "my home phone number is 312-111-1122 and my cell phone number is 312-555-1423.",
"detectors": {
"input": {
"pii": {}
}
},
"_prompt_masks": [[0, 37]]
}
```
Unrelated change (nit): dropped `let input_id = 0;` for consistency between unary and streaming handlers
NOTE: In Rust, leading underscores on field and variable names means "unused" rather than "internal" as in Python and they have special handling for …
> Add prompt masks for completions input detection

- src/clients.rs
- src/orchestrator/common/tasks.rs
- src/orchestrator/handlers/chat_completions_detection/streaming.rs
- src/orchestrator/handlers/chat_completions_detection/unary.rs
- src/orchestrator/handlers/classification_with_gen.rs
- src/orchestrator/handlers/completions_detection/streaming.rs
- src/orchestrator/handlers/completions_detection/unary.rs
- src/orchestrator/handlers/generation_with_detection.rs
- src/orchestrator/handlers/streaming_classification_with_gen.rs
This is a small nit PR to tweak the `ClientMap` get methods. Initial `get` and `get_mut` methods returned `&dyn Client` (trait object) as I anticipated we would use `get` for client health checks. We ultimately didn't use it as we have an `iter` method that iterates over all client trait objects, which is more convenient for performing health checks. As such, we do not need to have a separate set of unidiomatic `get_as` and `get_mut_as` methods to return concrete client types.
Changes:
- Drop existing `get` and `get_mut` methods
- Rename `get_as` and `get_mut_as` to `get` and `get_mut`, respectively
- Update usage
> Update ClientMap get methods

- src/health.rs
- src/models.rs
- src/orchestrator.rs
- src/server/routes.rs
This PR drops client health caching functionality as we determined it is not needed or used as initially intended. `/info` calls will now _always_ run client health probes (`probe=true` parameter is no longer required), returning the _current_ health status for all clients. Also tweaked a couple of logs and added in a warning log if any clients are unhealthy during startup probes. Tested locally and compared `/info` results with main to validate.
NOTE: I attempted to update `client_health()` to run client health checks concurrently, but I can't figure out how to work around a lifetime issue from the router related to having to use a reference to the client trait object (`&Box<dyn Client>`). I left the concurrent code commented out to further investigate. For now, the health checks will …
> Drop client health caching functionality

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/args.rs
- src/models.rs
- src/orchestrator/handlers/chat_completions_detection/streaming.rs
- src/orchestrator/handlers/completions_detection/streaming.rs
- src/orchestrator/types/chat_message.rs
In this PR:
1. Update Rust version to 1.89.0
2. Apply formatting and linting (new rules usually come out with new Rust releases)
3. Update non-breaking dependencies
> Preparation for release 0.14.0

- config/config.yaml
- src/config.rs
- src/orchestrator/common/utils.rs
This PR reverts a change merged in #463 to once again only allow a single detector type to be specified for a detector config. This is preferred to avoid detector type ambiguity issues now that we will enable support for multiple detector types on completions and chat completions endpoints.
Leaving `one_or_many` helper in utils in case we need it later.
> Revert DetectorConfig to only support single detector type

- Cargo.lock
- Cargo.toml
- build.rs
This is a follow-up on #486, as I'd forgotten to include tonic-related dependencies.
Summary:
* Updates `tonic`-related dependencies (including ginepro and mocktail, as they also depend on tonic).
* Drops `axum-test` as we no longer need it (and haven't been using it for a little while now).
> Update orchestrator tonic-related dependencies

- src/clients.rs
- src/config.rs
This PR makes keep-alive parameters configurable for gRPC clients.
> Make clients keep alive interval and timeout configurable

- Cargo.lock
- Cargo.toml
In this PR:
* Non-breaking dependency updates
* Update orchestrator crate version to `0.16.0`
> Preparation for release 0.16.0

- src/clients/openai.rs
- tests/chat_detection.rs
Changes:
- Add explicit `tools` field to `ChatCompletionRequest` (rather than untyped via `extra`) as it will be used by the orchestrator for chat detector requests
- Update `Tool` for alignment with openai spec, supporting both function tool and custom tool definitions
> Add tools field to ChatCompletionRequest, update Tool type

- Dockerfile.amd64
- Dockerfile.ppc64le
- Dockerfile.s390x
Container image builds were failing because `Cargo.lock` wasn't being added to the build environment. This PR fixes this issue.
> Add Cargo.lock to dockerfiles
